// Standalone test for the route parser. No JUnit — adding a test framework
// would put a dependency in a project whose entire argument is that it has
// none. Route.java imports nothing from Android, so plain javac runs it.
//
// From the repo root, with routes already generated by tools/seed-demo.mjs:
//
//   javac -d /tmp/rt tools/mockgps/app/src/main/java/com/roamkeep/mockgps/Route.java tools/mockgps/RouteTest.java
//   java -cp /tmp/rt RouteTest
//
// Exits non-zero on failure.

import com.roamkeep.mockgps.Route;

import java.io.ByteArrayInputStream;
import java.io.FileInputStream;
import java.io.IOException;

public class RouteTest {

    static int fail = 0;

    static void ok(String name, boolean cond, String detail) {
        System.out.println((cond ? "  ok   " : "  FAIL ") + name + (detail.isEmpty() ? "" : "  " + detail));
        if (!cond) fail++;
    }

    public static void main(String[] args) throws Exception {
        String dir = args.length > 0 ? args[0] : "store";

        for (String f : new String[]{"demo-drive.gpx", "demo-drive.kml", "demo-walk.gpx", "demo-walk.kml"}) {
            Route r = Route.parse(new FileInputStream(dir + "/" + f));
            ok(f + " parses", r.size() > 5,
                    r.format + " " + r.size() + " pts " + String.format("%.2f km", r.lengthM() / 1000));
        }

        Route gpx = Route.parse(new FileInputStream(dir + "/demo-drive.gpx"));
        Route kml = Route.parse(new FileInputStream(dir + "/demo-drive.kml"));
        ok("gpx and kml of the same route agree on length",
                Math.abs(gpx.lengthM() - kml.lengthM()) < 1.0,
                String.format("%.1f m vs %.1f m", gpx.lengthM(), kml.lengthM()));

        // KML is lng,lat and GPX is lat,lon. Getting that backwards produces
        // a perfectly valid route in the Gulf of Guinea, which is why this is
        // asserted against real coordinates rather than "it parsed".
        ok("kml coordinate order is not swapped",
                kml.lat[0] > 37 && kml.lat[0] < 38 && kml.lng[0] < -122 && kml.lng[0] > -123,
                kml.lat[0] + ", " + kml.lng[0]);

        // Deliberately not "the midpoint is at latitude X". That is a fact
        // about one route, and it broke the moment the demo geography moved
        // from a hand-drawn line to real roads. The property that actually
        // matters is that at() lands inside the route's own extent.
        double[] mid = gpx.at(gpx.lengthM() / 2);
        double minLat = 90, maxLat = -90, minLng = 180, maxLng = -180;
        for (int i = 0; i < gpx.size(); i++) {
            minLat = Math.min(minLat, gpx.lat[i]); maxLat = Math.max(maxLat, gpx.lat[i]);
            minLng = Math.min(minLng, gpx.lng[i]); maxLng = Math.max(maxLng, gpx.lng[i]);
        }
        ok("midpoint lands within the route's own bounding box",
                mid[0] >= minLat && mid[0] <= maxLat && mid[1] >= minLng && mid[1] <= maxLng,
                String.format("%.5f, %.5f", mid[0], mid[1]));
        ok("bearing is a compass value", mid[2] >= 0 && mid[2] < 360, String.format("%.0f deg", mid[2]));
        ok("clamps before the start", gpx.at(-5)[0] == gpx.lat[0], "");
        ok("clamps past the end", gpx.at(gpx.lengthM() + 5000)[0] == gpx.lat[gpx.size() - 1], "");

        // The point of interpolating: a file sampled every 110 m must still
        // yield a fix every second at walking pace, and consecutive fixes
        // must be one pace apart. A device that teleports is worse than one
        // that does not move.
        //
        // NOT a test that distance-from-start always increases. Real road
        // geometry curves back on itself — the drive route passes within
        // 300 m of its own origin — so that assertion failed on correct
        // output. Walking the arc and checking each step is the honest
        // version, and it also proves at() is not silently snapping to
        // source vertices.
        double step = 5 / 3.6;
        double walked = 0, biggest = 0;
        int n = 0;
        double[] prev = gpx.at(0);
        for (double m = step; m <= gpx.lengthM(); m += step) {
            double[] p = gpx.at(m);
            double d = Route.distance(prev[0], prev[1], p[0], p[1]);
            walked += d;
            biggest = Math.max(biggest, d);
            prev = p;
            n++;
        }
        ok("walking pace yields a fix every metre-and-a-bit, no jumps",
                biggest <= step * 1.02 && n > 1000,
                String.format("%d fixes, largest step %.2f m (pace is %.2f m)", n, biggest, step));
        ok("the interpolated path reconstructs the route's length",
                Math.abs(walked - gpx.lengthM()) < gpx.lengthM() * 0.01,
                String.format("%.0f m walked vs %.0f m route", walked, gpx.lengthM()));

        try {
            Route.parse(new ByteArrayInputStream("<html>not a route</html>".getBytes()));
            ok("rejects a non-route file", false, "");
        } catch (IOException e) {
            ok("rejects a non-route file", true, e.getMessage());
        }
        try {
            Route.parse(new ByteArrayInputStream("<gpx><trkpt lat=\"1\" lon=\"1\"></trkpt></gpx>".getBytes()));
            ok("rejects a one-point route", false, "");
        } catch (IOException e) {
            ok("rejects a one-point route", true, e.getMessage());
        }

        System.out.println(fail == 0 ? "\nall passed" : "\n" + fail + " FAILED");
        System.exit(fail == 0 ? 0 : 1);
    }
}
