#!/usr/bin/env node
//
// Seed the Play-review demo backend with an invented family.
//
//   node tools/seed-demo.mjs --ref <ref> --dry-run     # plan only, no network
//
//   $env:SUPABASE_ACCESS_TOKEN = "sbp_..."             # PowerShell
//   node tools/seed-demo.mjs --ref <demo-project-ref>
//
// WHY THIS EXISTS
// ---------------
// Play's "App access" field needs a reviewer to be able to USE the app, and
// Roamkeep cannot be used without a backend — a reviewer cannot provision a
// Supabase project. So one demo project exists purely for review.
//
// It must not be seeded from real devices. Doing that would put the author's
// home, school and daily movements into a database whose credentials are
// handed to Google and printed in a store listing. Everything here is
// invented: three fictional members, three places in Mountain View, and
// trails computed from a polyline.
//
// WHAT MAKES THE DATA LOOK REAL
// -----------------------------
// Naive seeding produces a History tab that renders wrong, because the app
// reconstructs a day from two different signals:
//
//   • STAYS come from arrived/left checkin PAIRS — never from breadcrumbs,
//     because the native writer suppresses breadcrumbs inside a saved place
//     (LocationUpdateReceiver.processLocations). So this omits any generated
//     point falling inside a place radius, exactly like the real writer.
//   • TRIPS come from breadcrumbs, split on a gap longer than TRIP_GAP_MS
//     (10 min) and classified walk/ride/drive from GPS speed (DRIVE_AVG_MS
//     8, RIDE_AVG_MS 2.2). The speeds below straddle those thresholds on
//     purpose, and --dry-run re-runs the app's own classifier to prove it.
//
// SAFETY
// ------
// This DELETES every member, place, checkin and breadcrumb in the target
// project before re-seeding. Two interlocks stop that reaching a real
// family: a refusal list of known-real refs, and a check that the project
// contains no keep other than this script's own demo keep.
//
// Re-run before submitting — location_history is pruned at 7 days, so a demo
// seeded a fortnight before review shows an empty History tab. Do NOT re-run
// while a review is in progress: member ids are regenerated, which
// invalidates a session the reviewer has already established.

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.join(HERE, '..');
const OUT = path.join(REPO, 'store');

/**
 * Projects that must never be seeded, because seeding WIPES the target.
 *
 * These used to be hardcoded, which named the author's own family database
 * in a repository that is about to be published. A Supabase ref is not a
 * secret — the anon key is public by design and RLS is the actual boundary —
 * but printing a real household's endpoint in a public file invites people
 * to go and test that boundary, for no benefit to anyone.
 *
 * So the list is assembled from sources that are gitignored:
 *
 *   • deploy.config.json's url — the owner's own backend, already on this
 *     machine and already excluded from git.
 *   • an optional `neverSeed` array in that same file, for anything else
 *     that has had real devices on it.
 *   • ROAMKEEP_NEVER_SEED, comma-separated, for a one-off.
 *
 * If none of those exist the list is empty, and the interlock further down —
 * refusing any project that holds a keep this script did not create — is the
 * one doing the work. That one needs no configuration and is the reason a
 * fresh clone is still safe.
 */
function refusalList() {
  const never = new Map();
  try {
    const cfg = JSON.parse(fs.readFileSync(path.join(REPO, 'deploy.config.json'), 'utf8'));
    const m = /https:\/\/([a-z0-9]+)\.supabase\.co/i.exec(cfg.url || '');
    if (m) never.set(m[1], "the project in deploy.config.json — the owner's own backend");
    for (const r of cfg.neverSeed || []) {
      never.set(String(r).trim(), 'listed in deploy.config.json neverSeed');
    }
  } catch { /* no deploy config on this machine — fine */ }
  for (const r of (process.env.ROAMKEEP_NEVER_SEED || '').split(',')) {
    if (r.trim()) never.set(r.trim(), 'listed in ROAMKEEP_NEVER_SEED');
  }
  return never;
}
const NEVER = refusalList();

const KEEP_NAME = 'Demo Family';

// Mirrors of app.js. If these drift, the seeded day stops classifying the
// way the timeline will render it.
const TRIP_GAP_MS = 10 * 60 * 1000;
const DRIVE_AVG_MS = 8;
const DRIVE_MAX_MS = 12.5;
const RIDE_AVG_MS = 2.2;

// Places and road geometry both come from tools/demo-routes.json, which is
// committed. It is generated by tools/fetch-demo-routes.mjs from a public
// routing service; caching it keeps this script offline and deterministic.
//
// Hand-picked waypoints were what the first version used, and the trails cut
// diagonally across blocks and through buildings — the one thing demo data
// must not look like. These follow actual roads.
//
// HOME sits on the Android emulator's default position, so a reviewer on a
// stock emulator opens the app already inside a saved place.
const GEO = JSON.parse(fs.readFileSync(path.join(HERE, 'demo-routes.json'), 'utf8'));
const PLACES = Object.entries(GEO.places).map(([key, p]) => ({ key, ...p }));
const P = Object.fromEntries(PLACES.map((p) => [p.key, p]));
const ROUTE_SCHOOL = GEO.routes.drive.coords;
const ROUTE_SHOPS = GEO.routes.walk.coords;

// Deliberately not plausible as real people. The credentials go to Google
// and may be read by anyone who inspects the listing.
const MEMBERS = [
  { key: 'parent', email: 'demo@roamkeep.app',       name: 'Demo Parent', avatar: '👩', member_type: 'adult', role: 'owner',  battery: 82 },
  { key: 'adult',  email: 'demo.adult@roamkeep.app', name: 'Demo Adult',  avatar: '👨', member_type: 'adult', role: 'member', battery: 64 },
  { key: 'child',  email: 'demo.child@roamkeep.app', name: 'Demo Child',  avatar: '👧', member_type: 'child', role: 'member', battery: 47 },
];
const M = Object.fromEntries(MEMBERS.map((m) => [m.key, m]));


// ── geometry ──────────────────────────────────────────────────

const R = 6371000;
const rad = (d) => (d * Math.PI) / 180;
function distanceM(aLat, aLng, bLat, bLng) {
  const dLat = rad(bLat - aLat), dLng = rad(bLng - aLng);
  const s = Math.sin(dLat / 2) ** 2 +
    Math.cos(rad(aLat)) * Math.cos(rad(bLat)) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(s));
}

/**
 * Evenly spaced points along a polyline, about `stepM` apart.
 *
 * A RESAMPLER, not a densifier. The earlier version only ever inserted
 * points between the source points, which was fine for a five-point
 * hand-drawn line and wrong for road geometry: OSRM emits vertices at every
 * kink, sometimes a metre apart, and subdividing those gave a "route"
 * whose fixes were 0 m apart — failing the 40 m displacement bar that the
 * whole 80 m sampling exists to clear.
 *
 * Spacing is uniform at total/n rather than exactly stepM, so the final
 * point lands on the destination instead of a stub segment shorter than the
 * rest.
 */
function resample(route, stepM) {
  const cum = [0];
  for (let i = 1; i < route.length; i++) {
    cum[i] = cum[i - 1] + distanceM(...route[i - 1], ...route[i]);
  }
  const total = cum[cum.length - 1];
  if (total <= 0) return [route[0], route[route.length - 1]];

  const n = Math.max(1, Math.round(total / stepM));
  const out = [];
  let seg = 1;
  for (let k = 0; k <= n; k++) {
    const target = (total * k) / n;
    while (seg < cum.length - 1 && cum[seg] < target) seg++;
    const a = route[seg - 1], b = route[seg];
    const segLen = cum[seg] - cum[seg - 1];
    const f = segLen <= 0 ? 0 : (target - cum[seg - 1]) / segLen;
    out.push([a[0] + (b[0] - a[0]) * f, a[1] + (b[1] - a[1]) * f]);
  }
  return out;
}

const insidePlace = (lat, lng) =>
  PLACES.some((p) => distanceM(lat, lng, p.lat, p.lng) <= p.radius_m);

const reverse = (route) => [...route].reverse();

/**
 * One trip's breadcrumbs. Points inside a place are dropped rather than
 * shifted — that is what the device does, and it is what makes History show
 * a stay followed by a trip instead of one continuous smear.
 */
function trip(route, startMs, speedMs, { stepM = 25, jitterM = 4 } = {}) {
  const pts = resample(route, stepM);
  const rows = [];
  let t = startMs;
  for (let i = 0; i < pts.length; i++) {
    if (i > 0) t += (distanceM(...pts[i - 1], ...pts[i]) / speedMs) * 1000;
    const [lat, lng] = pts[i];
    if (insidePlace(lat, lng)) continue;
    // Jitter is small on purpose. The geometry is road-snapped now, and
    // scattering it more than a lane's width would undo that by putting
    // breadcrumbs through front gardens.
    const jLat = (Math.random() - 0.5) * (jitterM / 111000) * 2;
    const jLng = (Math.random() - 0.5) * (jitterM / 88000) * 2;
    rows.push({
      lat: +(lat + jLat).toFixed(6),
      lng: +(lng + jLng).toFixed(6),
      speed: +(speedMs * (0.85 + Math.random() * 0.3)).toFixed(2),
      at: new Date(t),
    });
  }
  // `t` has run past every point, including the suppressed tail inside the
  // destination — so it is when the traveller actually got there, which is
  // what the arrival check-in should say. Deriving it beats a hardcoded
  // clock time that silently stops matching the route the moment the route
  // changes length.
  return { rows, endMs: t };
}

// ── the day plan (pure — no network) ──────────────────────────

function buildPlan() {
  for (const m of MEMBERS) m.id = crypto.randomUUID();
  for (const p of PLACES) p.id = crypto.randomUUID();

  const DAY = 86400000;
  const midnight = (offset) => {
    const d = new Date();
    d.setHours(0, 0, 0, 0);
    return d.getTime() - offset * DAY;
  };
  const at = (offset, h, min) => midnight(offset) + h * 3600000 + min * 60000;

  const breadcrumbs = [], checkins = [], arrived = {};

  // Nothing may be stamped in the future. Seeding at 07:00 would otherwise
  // file an 08:05 school run that has not happened, and the History tab
  // would show a trip ahead of the clock. Truncating instead of shifting
  // also gives a run mid-morning a genuinely in-progress trip.
  const now = Date.now();
  const checkin = (member, place, type, ms) => {
    if (ms > now) return;
    checkins.push({ member, place, type, at: new Date(ms) });
    if (type === 'arrived') arrived[member.key] = { place, at: new Date(ms) };
  };
  const record = (member, rows) => {
    for (const r of rows) if (r.at.getTime() <= now) breadcrumbs.push({ member, ...r });
  };

  /**
   * One complete journey: left A, a trail, arrived B.
   *
   * The arrival time comes from the trip itself rather than a hardcoded
   * clock time. With road geometry the legs are whatever length the roads
   * make them, and a fixed "arrived at 08:18" would quietly stop matching
   * the trail the moment a place moved.
   *
   * @return the arrival time, so the caller can schedule what follows.
   */
  const journey = (member, route, startMs, speedMs, fromPlace, toPlace) => {
    checkin(member, fromPlace, 'left', startMs);
    const { rows, endMs } = trip(route, startMs, speedMs);
    record(member, rows);
    if (toPlace) checkin(member, toPlace, 'arrived', endMs);
    return endMs;
  };

  // The two previous days are a routine on the clock: out in the morning,
  // back in the afternoon.
  const DRIVE_MS = 11, DRIVE_HOME_MS = 10.5, WALK_MS = 1.35, WALK_HOME_MS = 1.3;
  for (let d = 2; d >= 1; d--) {
    journey(M.child, ROUTE_SCHOOL, at(d, 8, 5), DRIVE_MS, P.home, P.school);
    journey(M.child, reverse(ROUTE_SCHOOL), at(d, 15, 30), DRIVE_HOME_MS, P.school, P.home);

    const shopped = journey(M.adult, ROUTE_SHOPS, at(d, 10, 15), WALK_MS, P.home, P.shops);
    // Twenty-five minutes in the shop, then home — scheduled off the actual
    // arrival so the stay is a stay and not an overlap.
    journey(M.adult, reverse(ROUTE_SHOPS), shopped + 25 * 60000, WALK_HOME_MS, P.shops, P.home);
  }

  // Today is anchored to NOW, not to the clock. Fixed morning slots would
  // leave a demo seeded in the evening showing a family that has not moved
  // for nine hours, and a demo seeded before breakfast showing nothing at
  // all. Relative offsets give a live-looking map whenever it is run.
  const ago = (mins) => now - mins * 60000;

  // Child drove to school a while back and is still there. Started far
  // enough back that the whole leg has finished whatever the route length.
  journey(M.child, ROUTE_SCHOOL, ago(95), DRIVE_MS, P.home, P.school);

  // Adult is still walking — no destination passed, so no arrival check-in,
  // and record() truncates the trail at now. That leaves one member visibly
  // in motion with a live trail behind them, which is the state worth
  // photographing.
  journey(M.adult, ROUTE_SHOPS, ago(8), WALK_MS, P.home, null);

  breadcrumbs.sort((a, b) => a.at - b.at);
  checkins.sort((a, b) => a.at - b.at);

  /**
   * Where each member's map pin sits.
   *
   * Not simply "the last breadcrumb": a trip that ends at a place has its
   * final points suppressed inside the radius, so the last breadcrumb is
   * always on the boundary — every arrived member would be pinned to the
   * edge of their own garden. An arrival check-in that is NEWER than the
   * last breadcrumb is the signal that the journey finished, and it wins.
   */
  const RECENT_MS = 2 * 3600000;
  const pin = (m) => {
    const mine = breadcrumbs.filter((b) => b.member.key === m.key);
    const last = mine[mine.length - 1];
    const a = arrived[m.key];
    const stillOut = last && now - last.at.getTime() < RECENT_MS &&
      (!a || a.at.getTime() < last.at.getTime());
    if (stillOut) return { lat: last.lat, lng: last.lng, seen: last.at };
    const p = a ? a.place : P.home;
    // A few metres off centre, or three members stack into one dot.
    const off = (n) => (((m.key.charCodeAt(0) * n) % 7) - 3) * 0.00015;
    return {
      lat: +(p.lat + off(3)).toFixed(6),
      lng: +(p.lng + off(5)).toFixed(6),
      seen: a ? a.at : new Date(now - 15 * 60000),
    };
  };
  return { breadcrumbs, checkins, pin };
}

/**
 * app.js tripStats/segmentTrips, close enough to check what will render.
 *
 * "Close enough" has to include the EMISSION filter, or the dry run asserts
 * something the app does not do. It used to skip even TRIP_MIN_M; now that
 * app.js also requires a trip to have gone somewhere (spanM) and splits on a
 * stationary stretch as well as a silence, this mirrors both. If it drifts
 * from app.js again, the dry run goes back to quietly blessing seeds the
 * timeline will refuse to show.
 */
const TRIP_MIN_M = 120;
const TRIP_SPAN_MIN_M = 120;
const STILL_RADIUS_M = 120;
const STILL_WINDOW_MS = 15 * 60 * 1000;
function classify(rows) {
  const trips = [];
  let cur = null, lastT = null, anchor = null;
  for (const p of rows) {
    const t = p.at.getTime();
    const gap = !!(cur && lastT != null && t - lastT > TRIP_GAP_MS);
    if (!gap && anchor) {
      if (distanceM(anchor.lat, anchor.lng, p.lat, p.lng) > STILL_RADIUS_M) {
        anchor = { lat: p.lat, lng: p.lng, t };
      } else if (t - anchor.t > STILL_WINDOW_MS) {
        cur = null; continue;
      }
    }
    if (!cur || gap) { cur = []; trips.push(cur); anchor = { lat: p.lat, lng: p.lng, t }; }
    cur.push(p); lastT = t;
  }
  return trips.filter((t) => t.length >= 2).map((t) => {
    let distM = 0, spanM = 0, maxSp = 0, sum = 0;
    for (let i = 1; i < t.length; i++) distM += distanceM(t[i - 1].lat, t[i - 1].lng, t[i].lat, t[i].lng);
    for (const p of t) spanM = Math.max(spanM, distanceM(t[0].lat, t[0].lng, p.lat, p.lng));
    for (const p of t) { maxSp = Math.max(maxSp, p.speed); sum += p.speed; }
    const avgSp = sum / t.length;
    const mode = (avgSp >= DRIVE_AVG_MS || maxSp >= DRIVE_MAX_MS) ? 'drive'
               : (avgSp >= RIDE_AVG_MS) ? 'ride' : 'walk';
    return { mode, distM, spanM, avgSp, n: t.length, start: t[0].at };
  }).filter((t) => t.distM >= TRIP_MIN_M && t.spanM >= TRIP_SPAN_MIN_M);
}

// ── SQL helpers ───────────────────────────────────────────────

const q = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const iso = (d) => d.toISOString();

// ── main ──────────────────────────────────────────────────────

const arg = (n) => {
  const i = process.argv.indexOf('--' + n);
  return i > -1 ? process.argv[i + 1] : null;
};
const has = (n) => process.argv.includes('--' + n);

function die(msg) {
  console.error('\n  ' + msg + '\n');
  process.exit(1);
}
const say = (s) => console.log('  ' + s);

const ref = arg('ref');
const dryRun = has('dry-run');
if (!ref) die('Usage: node tools/seed-demo.mjs --ref <project-ref> [--dry-run]');
if (NEVER.has(ref)) {
  die(`Refusing to seed ${ref} — that is ${NEVER.get(ref)}.\n` +
      '  Seeding wipes every member, place, check-in and breadcrumb in the project.');
}

const projectUrl = `https://${ref}.supabase.co`;
const plan = buildPlan();

/**
 * Routes for a mock-location player, in both formats worth having.
 *
 * GPX carries a <time> per point, so a player that steps point-to-point
 * (the Android emulator does) gets its pacing from the file. KML is a bare
 * LineString with no timing at all — several mock apps only import KML, and
 * they interpolate along the path at a speed you set in their UI.
 *
 * Points are 80 m apart. That matters only for a player that does NOT
 * interpolate: each delivered fix must clear the 40 m displacement bar in
 * LocationForegroundService.detectMoving, because a mocked fix often carries
 * no speed and displacement is then the only evidence of motion. A route
 * sampled every 15 m can read as a stationary device, and the trail never
 * densifies. For an interpolating player the spacing is merely cosmetic.
 */
// 110 m rather than the 40 m bar, because the bar applies to STRAIGHT-LINE
// displacement between consecutive fixes and these points are spaced along
// the ARC. At a right-angle turn the straight-line gap is much shorter than
// the arc between the same two points — 80 m sampling measured 43 m at the
// tightest corner, passing by 3 m. 110 m leaves real margin.
const ROUTE_STEP_M = 110;
const ROUTE_STEP_MS = 8000;  // 110 m / 8 s ≈ 50 km/h — urban, not motorway
const ROUTE_EPOCH = Date.parse('2026-01-01T09:00:00Z');

function writeRoute(slug, title, route) {
  const pts = resample(route, ROUTE_STEP_M);
  const gpx = path.join(OUT, `${slug}.gpx`);
  const kml = path.join(OUT, `${slug}.kml`);

  fs.writeFileSync(gpx, `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="roamkeep-seed-demo" xmlns="http://www.topografix.com/GPX/1/1">
  <trk><name>${title}</name><trkseg>
${pts.map(([lat, lng], i) =>
    `    <trkpt lat="${lat.toFixed(6)}" lon="${lng.toFixed(6)}">` +
    `<time>${new Date(ROUTE_EPOCH + i * ROUTE_STEP_MS).toISOString()}</time></trkpt>`).join('\n')}
  </trkseg></trk>
</gpx>
`);

  fs.writeFileSync(kml, `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>${title}</name>
  <Placemark><name>${title}</name><LineString><tessellate>1</tessellate>
    <coordinates>
${pts.map(([lat, lng]) => `      ${lng.toFixed(6)},${lat.toFixed(6)},0`).join('\n')}
    </coordinates>
  </LineString></Placemark>
</Document></kml>
`);

  let min = Infinity, total = 0;
  for (let i = 1; i < pts.length; i++) {
    const d = distanceM(...pts[i - 1], ...pts[i]);
    min = Math.min(min, d); total += d;
  }
  return { slug, pts: pts.length, min, km: total / 1000, gpx, kml };
}

fs.mkdirSync(OUT, { recursive: true });
const ROUTES = [
  writeRoute('demo-drive', 'Roamkeep demo — Home to School (drive)', ROUTE_SCHOOL),
  writeRoute('demo-walk', 'Roamkeep demo — Home to Shops (walk)', ROUTE_SHOPS),
];

console.log('');
say(`project    ${projectUrl}${dryRun ? '   (dry run — nothing will be written to it)' : ''}`);
// A refusal list that says nothing is a refusal list nobody notices has
// gone empty — which is exactly what happens on a machine with no
// deploy.config.json.
say(`guarded    ${NEVER.size} ref(s) on the refusal list` +
    (NEVER.size ? '' : ' — none configured; the foreign-keep check is the only interlock'));
say(`plan       ${MEMBERS.length} members · ${PLACES.length} places · ` +
    `${plan.checkins.length} check-ins · ${plan.breadcrumbs.length} breadcrumbs`);

{
  // Prove the seeded speeds land where the timeline expects them, rather
  // than assuming. A walk that classifies as a drive is a demo that
  // demonstrates the wrong thing.
  const rows = [];
  let bad = 0;
  for (const m of MEMBERS) {
    const mine = plan.breadcrumbs.filter((b) => b.member.key === m.key);
    if (!mine.length) continue;
    for (const t of classify(mine)) {
      const want = m.key === 'child' ? 'drive' : 'walk';
      if (t.mode !== want) bad++;
      rows.push(`${m.name.padEnd(12)} ${t.start.toISOString().slice(5, 16).replace('T', ' ')}  ` +
        `${t.mode.padEnd(5)} ${(t.distM / 1000).toFixed(2)} km  ${t.n} pts  avg ${t.avgSp.toFixed(1)} m/s`);
    }
  }
  say(`trips      ${rows.length} across 3 days`);
  for (const r of rows) console.log('             ' + r);
  say((bad === 0 ? 'ok         ' : 'FAIL       ') +
      `every trip classifies as intended (drive for the school run, walk for the shops)`);
  if (bad) die('Adjust the speeds in buildPlan() — the timeline would label these wrong.');
}
{
  say('pins       where each member shows on the map right now');
  for (const m of MEMBERS) {
    const p = plan.pin(m);
    const at = PLACES.find((pl) => distanceM(p.lat, p.lng, pl.lat, pl.lng) <= pl.radius_m);
    const mins = Math.round((Date.now() - p.seen.getTime()) / 60000);
    console.log(`             ${m.name.padEnd(12)} ${(at ? at.icon + ' ' + at.name : 'en route').padEnd(12)}` +
      ` ${p.lat.toFixed(5)}, ${p.lng.toFixed(5)}   seen ${mins} min ago`);
  }
}
{
  say('routes     for a mock-location player — .gpx and .kml of each');
  for (const r of ROUTES) {
    console.log(`             ${r.slug.padEnd(11)} ${String(r.pts).padStart(3)} pts  ` +
      `${r.km.toFixed(2)} km  ~${Math.round(r.min)} m apart  ` +
      `(${(r.min / (ROUTE_STEP_MS / 1000) * 3.6).toFixed(0)} km/h if stepped)`);
  }
  const worst = Math.min(...ROUTES.map((r) => r.min));
  say((worst > 40 ? 'ok         ' : 'FAIL       ') +
      'every fix clears the 40 m displacement bar in detectMoving');
  say(`           written to ${path.relative(REPO, OUT)}${path.sep}`);
}

if (dryRun) {
  console.log('');
  say('Dry run only. Re-run without --dry-run to create the logins and seed the project.');
  console.log('');
  process.exit(0);
}

// `set VAR=value` is cmd.exe. In PowerShell `set` aliases Set-Variable,
// which happily creates a shell variable named "VAR=value" holding nothing,
// reports no error, and leaves the environment untouched — so the token
// looks set and this script sees nothing. Spell out the right syntax rather
// than naming the variable and leaving the reader to guess the shell.
const token = process.env.SUPABASE_ACCESS_TOKEN;
if (!token) {
  die('No SUPABASE_ACCESS_TOKEN in the environment.\n\n' +
      '  PowerShell:   $env:SUPABASE_ACCESS_TOKEN = "sbp_..."\n' +
      '  cmd.exe:      set SUPABASE_ACCESS_TOKEN=sbp_...\n' +
      '  bash:         export SUPABASE_ACCESS_TOKEN=sbp_...\n\n' +
      '  It has to be the same window you then run this in, and it does not\n' +
      '  survive closing it. Create one at:\n' +
      '  https://supabase.com/dashboard/account/tokens');
}

const { createClient } = await import('../cli/src/api.js');
const { buildSetupLink } = await import('../cli/src/link.js');
const steps = await import('../cli/src/steps.js');

const api = createClient(token);

// A missing schema means the wizard was never run against this project, and
// every insert below would fail one at a time instead of once, clearly.
await steps.verifySchema(api, ref).catch((e) =>
  die(`Schema check failed: ${e.message}\n  Run the wizard against ${ref} first: cd cli && npm start`));
say('schema     present');

// The service_role key is used only to create the demo logins through the
// Auth admin API, and is never printed or written to disk.
const keys = await api.getApiKeys(ref);
const keyNamed = (n) => keys.find((k) => k.name === n || k.name === n + ' key')?.api_key;
const anonKey = keyNamed('anon');
const serviceKey = keyNamed('service_role');
if (!anonKey || !serviceKey) die('Could not read the project API keys.');

const existing = await api.query(ref, 'select id, name from keeps;');
const foreign = (existing || []).filter((k) => k.name !== KEEP_NAME);
if (foreign.length) {
  die(`${ref} contains a keep this script did not create: ${foreign.map((k) => k.name).join(', ')}.\n` +
      '  Refusing to wipe it. Use a project created solely for review.');
}

// Passwords persist across re-seeds — they are already in the Console.
const credFile = path.join(REPO, `roamkeep-demo-${ref}.json`);
const creds = fs.existsSync(credFile)
  ? JSON.parse(fs.readFileSync(credFile, 'utf8'))
  : { passwords: {} };
for (const m of MEMBERS) {
  if (!creds.passwords[m.email]) creds.passwords[m.email] = 'Demo-' + crypto.randomBytes(9).toString('base64url');
}

async function auth(method, p, body) {
  const res = await fetch(`${projectUrl}/auth/v1${p}`, {
    method,
    headers: {
      apikey: serviceKey,
      Authorization: `Bearer ${serviceKey}`,
      'Content-Type': 'application/json',
    },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await res.text();
  let json = null;
  try { json = text ? JSON.parse(text) : null; } catch { /* raw */ }
  return { ok: res.ok, status: res.status, json, text };
}

const listed = await auth('GET', '/admin/users?per_page=200');
if (!listed.ok) die(`Could not list users: ${listed.status} ${listed.text.slice(0, 200)}`);
const byEmail = new Map((listed.json?.users || []).map((u) => [String(u.email).toLowerCase(), u]));

for (const m of MEMBERS) {
  const pw = creds.passwords[m.email];
  const found = byEmail.get(m.email.toLowerCase());
  // Reset rather than skip, so the file on disk is always the truth.
  const r = found
    ? await auth('PUT', `/admin/users/${found.id}`, { password: pw, email_confirm: true })
    : await auth('POST', '/admin/users', { email: m.email, password: pw, email_confirm: true });
  if (!r.ok) die(`Could not provision ${m.email}: ${r.status} ${r.text.slice(0, 200)}`);
  m.uid = found ? found.id : r.json.id;
}
say(`logins     ${MEMBERS.length} ready`);

// Created directly rather than through create_keep(), which requires an
// authenticated caller and always makes the creator the owner — here the
// roles are chosen. The code gets a year rather than the RPC's 72 hours so
// nothing in Settings reads as expired on camera.
let keepId = existing?.[0]?.id;
if (keepId) {
  await api.query(ref, `update keeps set code_expires_at = now() + interval '365 days' where id = ${q(keepId)};`);
  say('keep       reused');
} else {
  const made = await api.query(ref, `
    insert into keeps (code, name, created_by, code_expires_at)
    values (_roamkeep_gen_code(), ${q(KEEP_NAME)}, ${q(MEMBERS[0].uid)}, now() + interval '365 days')
    returning id;`);
  keepId = made[0].id;
  say('keep       created');
}

// keep_members cascades to checkins and location_history, so this is the
// whole wipe. Members are replaced rather than updated because the guard
// trigger rejects an UPDATE that changes role or member_type.
await api.query(ref, `
  delete from keep_members where keep_id = ${q(keepId)};
  delete from keep_places  where keep_id = ${q(keepId)};`);

await api.query(ref, `
  insert into keep_places (id, keep_id, name, icon, lat, lng, radius_m, created_by) values
  ${PLACES.map((p) => `(${q(p.id)}, ${q(keepId)}, ${q(p.name)}, ${q(p.icon)}, ${p.lat}, ${p.lng}, ${p.radius_m}, ${q(MEMBERS[0].uid)})`).join(',\n  ')};`);

await api.query(ref, `
  insert into keep_members
    (id, keep_id, user_id, name, avatar, lat, lng, battery, member_type, role, online, last_seen) values
  ${MEMBERS.map((m) => {
    const p = plan.pin(m);
    return `(${q(m.id)}, ${q(keepId)}, ${q(m.uid)}, ${q(m.name)}, ${q(m.avatar)}, ${p.lat}, ${p.lng}, ` +
           `${m.battery}, ${q(m.member_type)}, ${q(m.role)}, true, ${q(iso(p.seen))})`;
  }).join(',\n  ')};`);

// Chunked: a few hundred rows in one statement is fine, a few thousand is
// not, and the count grows with any edit to the day plan.
const CHUNK = 400;
for (let i = 0; i < plan.breadcrumbs.length; i += CHUNK) {
  const rows = plan.breadcrumbs.slice(i, i + CHUNK);
  await api.query(ref, `
    insert into location_history (keep_id, member_id, lat, lng, speed, recorded_at) values
    ${rows.map((b) => `(${q(keepId)}, ${q(b.member.id)}, ${b.lat}, ${b.lng}, ${b.speed}, ${q(iso(b.at))})`).join(',\n    ')};`);
}

await api.query(ref, `
  insert into checkins (keep_id, member_id, member_name, member_avatar, place, type, created_at) values
  ${plan.checkins.map((c) => `(${q(keepId)}, ${q(c.member.id)}, ${q(c.member.name)}, ${q(c.member.avatar)}, ` +
    `${q(c.place.name)}, ${q(c.type)}, ${q(iso(c.at))})`).join(',\n  ')};`);

say('seeded     ok');

const link = buildSetupLink(projectUrl, anonKey);
Object.assign(creds, { ref, projectUrl, link, seededAt: new Date().toISOString() });
fs.writeFileSync(credFile, JSON.stringify(creds, null, 2));

const txt = [
  'Roamkeep — demo backend for Play review',
  `Project : ${projectUrl}`,
  `Seeded  : ${creds.seededAt}`,
  '',
  'Setup link (no invite code — a reviewer signs in, they do not join):',
  link,
  '',
  'Sign in as (put the first one in Play Console -> App access):',
  ...MEMBERS.map((m) => `  ${m.name.padEnd(12)} ${m.email.padEnd(26)} ${creds.passwords[m.email]}`),
  '',
  'Treat all of the above as public. Nothing real is in this project.',
  '',
  'Breadcrumbs are pruned at 7 days. Re-run the seeder if review has not',
  `started within a week of ${creds.seededAt.slice(0, 10)} — but never mid-review,`,
  'which regenerates member ids and breaks a session already established.',
].join('\n');
const txtFile = path.join(REPO, `roamkeep-demo-${ref}.txt`);
fs.writeFileSync(txtFile, txt);

console.log('');
console.log(txt.split('\n').map((l) => '  ' + l).join('\n'));
console.log('');
say(`written    ${path.relative(REPO, txtFile)}`);
say(`           ${path.relative(REPO, credFile)}   (passwords — reused on re-seed)`);
console.log('');
